# Generated by Django 4.2.27 on 2025-12-18 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=80, unique=True)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(default='student', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.appuser')),
            ],
            options={
                'db_table': 'course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.IntegerField(primary_key=True, serialize=False)),
                ('overall_score', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('usefulness', models.IntegerField()),
                ('workload', models.IntegerField()),
                ('comment_text', models.TextField(blank=True, null=True)),
                ('anonymous_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='core.appuser')),
            ],
            options={
                'db_table': 'rating',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('school_type', models.CharField(default='university', max_length=20)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'school',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tag',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reported_entity_type', models.CharField(max_length=20)),
                ('entity_id', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(db_column='reporter_id', on_delete=django.db.models.deletion.CASCADE, to='core.appuser')),
            ],
            options={
                'db_table': 'report',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RatingReaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.ForeignKey(db_column='rating_id', on_delete=django.db.models.deletion.CASCADE, to='core.rating')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='core.appuser')),
            ],
            options={
                'db_table': 'rating_reaction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('profile', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(db_column='school_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school')),
            ],
            options={
                'db_table': 'instructor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='core.appuser')),
            ],
            options={
                'db_table': 'favorite',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='core.tag')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='core.appuser')),
            ],
            options={
                'db_table': 'course_tag',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('semester', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('instructor', models.ForeignKey(db_column='instructor_id', on_delete=django.db.models.deletion.CASCADE, to='core.instructor')),
            ],
            options={
                'db_table': 'course_instructor',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(db_column='school_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('parent_comment', models.ForeignKey(db_column='parent_comment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.comment')),
                ('rating', models.ForeignKey(db_column='rating_id', on_delete=django.db.models.deletion.CASCADE, to='core.rating')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='core.appuser')),
            ],
            options={
                'db_table': 'comment',
                'managed': True,
            },
        ),
    ]
