# Generated by Django 4.2.27 on 2025-12-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_comment_user_alter_course_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('university', 'university'), ('highschool', 'highschool')], default='university', max_length=20),
        ),
    ]
