# Generated by Django 4.2.27 on 2025-12-18 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
    ]
