# Generated by Django 4.2.27 on 2025-12-29 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userdisclaimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='instructor',
            field=models.ForeignKey(db_column='instructor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.instructor'),
        ),
    ]
